In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression


In [5]:
data = pd.read_csv('dataset\Social_Network_Ads.csv')
data

<>:1: SyntaxWarning: invalid escape sequence '\S'
<>:1: SyntaxWarning: invalid escape sequence '\S'
C:\Users\dyes\AppData\Local\Temp\ipykernel_76876\3988853864.py:1: SyntaxWarning: invalid escape sequence '\S'
  data = pd.read_csv('dataset\Social_Network_Ads.csv')


User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [15]:
x = data.iloc[: ,[2,3]].values
y = data.iloc[:, 4].values

In [7]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test =  train_test_split(x, y, test_size= 0.2, random_state=43)

In [8]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
x_train  = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [9]:
x_train

array([[ 4.26622465e-01, -1.18318767e-01],
       [-3.44672387e-01, -7.57585164e-01],
       [ 1.10150546e+00, -1.19344862e+00],
       [-1.51848674e-01, -4.96067093e-01],
       [-8.26731669e-01,  1.72256869e-01],
       [-1.21237909e+00, -1.36779400e+00],
       [ 9.08681747e-01, -7.57585164e-01],
       [-2.48260530e-01, -1.36779400e+00],
       [ 1.00509360e+00,  7.82465703e-01],
       [-2.48260530e-01,  2.88487123e-01],
       [-1.50161466e+00, -4.08894402e-01],
       [-1.79085023e+00,  2.69690512e-02],
       [-1.51848674e-01,  1.62513505e+00],
       [ 7.15858034e-01, -1.07721836e+00],
       [ 1.37386895e-01,  1.72256869e-01],
       [-9.23143525e-01,  5.20947631e-01],
       [ 3.30210608e-01,  8.50841782e-02],
       [ 2.33798752e-01,  2.11911363e+00],
       [-5.37496100e-01,  4.91890068e-01],
       [ 8.12269891e-01, -1.19344862e+00],
       [-1.40520281e+00, -1.42590913e+00],
       [-8.26731669e-01, -1.19344862e+00],
       [ 1.39074103e+00,  2.35157413e+00],
       [ 1.

In [10]:
x_test

array([[-1.30879095, -0.4088944 ],
       [ 2.06562402,  0.20131443],
       [ 1.0050936 , -1.0481608 ],
       [-1.59802652,  0.08508418],
       [ 2.16203588,  0.95681108],
       [ 0.23379875,  0.05602661],
       [ 0.71585803, -1.367794  ],
       [ 0.04097504, -0.55418222],
       [ 0.81226989, -0.81570029],
       [-1.79085023, -1.28062131],
       [-0.92314353, -0.29266415],
       [-0.63390796, -0.0892612 ],
       [-0.82673167,  0.40471738],
       [-1.69443838, -0.58323978],
       [ 1.48715289, -1.01910324],
       [ 0.61944618,  2.03194094],
       [-0.73031981,  0.57906276],
       [ 2.16203588, -1.01910324],
       [-0.15184867,  1.4217321 ],
       [ 0.04097504, -0.23454902],
       [ 1.0050936 ,  0.14319931],
       [ 2.06562402,  0.40471738],
       [ 0.90868175, -1.13533349],
       [ 0.23379875,  0.08508418],
       [ 1.29432917, -1.33873644],
       [-1.69443838,  0.37565981],
       [-1.40520281,  0.37565981],
       [ 1.77638845,  1.01492621],
       [-0.63390796,

In [11]:
logistic_reg = LogisticRegression()
logistic_reg.fit(x_train, y_train)

LogisticRegression()

In [12]:
logistic_reg.predict(x_test)

array([0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0], dtype=int64)

In [13]:
print(f"Accuracy of the Logistic regression model is {(logistic_reg.score(x_train,y_train)) * 100} %")

Accuracy of the Logistic regression model is 86.25 %


In [14]:
import gradio as gr

In [16]:
def predict(age, salary):
    input_data = sc.transform([[age, salary]])
    prediction = logistic_reg.predict(input_data)
    return "Will Purchase the BMW car" if prediction[0] == 1 else "Will Not Purchase the BMW car"

In [18]:
iface = gr.Interface(fn=predict, 
                     inputs=["number", "number"], 
                     outputs="text",
                     title="Logistic Regression Model for Purchase Prediction",
                     description="Enter Age and Estimated Salary to predict whether a person will purchase the BMW or not.")

In [19]:
iface.launch()

Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
